// laravel_breeze_react/resources/js/Pages/Posts/Create.jsx
import { useForm } from "@inertiajs/react";
import React from "react";

export default function Create() {

    const{data, setData, errors, post} = useForm({
        title: "",
        body: ""
    })

    function handleSubmit(e) {
        e.preventDefault();
        post(route("post.store"));
        //alert("Data Sent");

    }
    //console.log(data);

    return (
        <>
            <h1>Post Entry</h1>
            <form action="" onSubmit={handleSubmit}>

                Title: <br/><input type="text" name="title" placeholder="Enter Title" value={data.title} onChange={(e)=>setData("title", e.target.value)} /><span className="text-red-600">{errors.title}</span><br />
                Body: <br/><textarea
                    name="body" placeholder="Enter Body" onChange={(e)=>setData("body", e.target.value)}
                >{data.body}</textarea><span className="text-red-600">{errors.body}</span><br />
            <button type="submit" className="px-6 py-2 font-bold text-white bg-green-500 rounded">SUBMIT</button>

            </form>
        </>
    );
}

// laravel_breeze_inertia_vue/resources/js/Pages/Post/Create.vue
<script setup>
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue';
import { useForm, Link } from "@inertiajs/vue3";

const form = useForm({
    title: "",
    body: "",
});

const submit = () => {
    form.post("/posts");
};
</script>

<template>
    <Head title="Manage Posts" />

    <AuthenticatedLayout>
        <template #header>
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">Create Post</h2>
        </template>

        <div class="py-12">
            <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
                <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                    <div class="p-6 text-gray-900">
                        <Link href="/posts"><button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded my-3">Back</button></Link>
                        
                        <form @submit.prevent="submit">
                            <div class="mb-4">
                                <label 
                                    for="title" 
                                    class="block text-gray-700 text-sm font-bold mb-2">
                                    Title:</label>
                                <input 
                                    type="text" 
                                    class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" 
                                    placeholder="Enter Title" 
                                    id="title"
                                    v-model="form.title" />

                            </div>

                            <div class="mb-4">
                                <label 
                                    for="body" 
                                    class="block text-gray-700 text-sm font-bold mb-2">
                                    Body:</label>
                                <textarea 
                                    class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="body" 
                                    v-model="form.body" 
                                    placeholder="Enter Body"></textarea>
                            </div>

                            <button type="submit" class="bg-green-500 hover:bg-orange-700 text-white font-bold py-2 px-4 rounded my-3 text-white">
                                Submit
                            </button>

                        </form>

                    </div>
                </div>
            </div>
        </div>
    </AuthenticatedLayout>
</template>
